<?xml version="1.0"?>
<package format="2">
  <name>pi05_control</name>
  <version>0.1.0</version>
  <description>Safety conditioning and ROS adapters for PI05 Pika-to-Piper control.</description>
  <maintainer email="maintainer@example.com">PI05 Maintainer</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>diagnostic_msgs</depend>
  <depend>rospy</depend>
  <exec_depend>rosgraph</exec_depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <exec_depend>data_msgs</exec_depend>
  <exec_depend>piper_msgs</exec_depend>

  <export/>
</package>
